apiVersion: v1
kind: Service
metadata:
  name: json-server-1
spec:
  selector:
    app: json-server-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: json-server-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server-1
  labels:
    app: json-server-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-server-1
  template:
    metadata:
      labels:
        app: json-server-1
    spec:
      containers:
      - name: json-server-1
        image: clue/json-server
        volumeMounts:
          - name: json-server-1
            mountPath: /data
        ports:
        - containerPort: 80
      initContainers:
      - name: json-server-seeder
        image: busybox
        command: ['sh', '-c', 'mkdir /data; echo "{\"posts\": [ { \"id\": 1, \"title\": \"json-server-1\", \"author\": \"typicode\" } ],  \"comments\": [ { \"id\": 1, \"body\": \"some comment 1\", \"postId\": 1 } ], \"profile\": { \"name\": \"typicode 1\" }}" > /data/db.json']
        volumeMounts:
          - name: json-server-1
            mountPath: /data
      volumes:
        - name: json-server-1
          persistentVolumeClaim:
            claimName: json-server-1
---
apiVersion: v1
kind: Service
metadata:
  name: json-server-2
spec:
  selector:
    app: json-server-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: json-server-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server-2
  labels:
    app: json-server-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-server-2
  template:
    metadata:
      labels:
        app: json-server-2
    spec:
      containers:
      - name: json-server-2
        image: clue/json-server
        volumeMounts:
          - name: json-server-2
            mountPath: /data
        ports:
        - containerPort: 80
      initContainers:
      - name: json-server-seeder
        image: busybox
        command: ['sh', '-c', 'mkdir /data; echo "{\"posts\": [ { \"id\": 1, \"title\": \"json-server-2\", \"author\": \"typicode\" } ],  \"comments\": [ { \"id\": 1, \"body\": \"some comment 2\", \"postId\": 1 } ], \"profile\": { \"name\": \"typicode 2\" }}" > /data/db.json']
        volumeMounts:
          - name: json-server-2
            mountPath: /data
      volumes:
        - name: json-server-2
          persistentVolumeClaim:
            claimName: json-server-2
