apiVersion: charts.helm.k8s.io/v1alpha1
kind: Kong
metadata:
  name: example-kong
spec:
  image:
    repository: kong-for-kong-operator
    tag: latest
    pullPolicy: Never
  proxy:
    type: NodePort
  env:
    prefix: /kong_prefix/
    database: "off"
  resources:
    limits:
      cpu: 500m
      memory: 1G
    requests:
      cpu: 100m
      memory: 200Mi
  ingressController:
    enabled: true
    installCRDs: false
  plugins:
    configMaps:
    - name: kong-plugin-oidc
      pluginName: oidc
